#Working on Dataset

In [59]:
import pandas as pd
import numpy as np

In [60]:
#Load Dataset

df = pd.read_csv("customer_support_tickets.csv")
df.head()

,Ticket_ID,Customer_ID,Region,Issue_Type,Priority,Status,Created_Date,Resolved_Date,Resolution_Time_Hours,Agent,Customer_Satisfaction
0,T001,C101,North,Login Issue,High,Closed,01-01-2025,01-01-2025,3,Rahul,4
1,T002,C102,West,Payment Issue,Medium,Closed,01-01-2025,02-01-2025,6,Sneha,5
2,T003,C103,South,Account Locked,High,Closed,02-01-2025,02-01-2025,4,Amit,3
3,T004,C104,East,Login Issue,Low,Closed,02-01-2025,03-01-2025,5,Neha,4
4,T005,C105,North,Refund Issue,High,Closed,03-01-2025,03-01-2025,2,Rahul,5

In [61]:
#Size of Database

df.shape

(100, 11)

In [62]:
#Structure

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              100 non-null    object
 1   Customer_ID            100 non-null    object
 2   Region                 100 non-null    object
 3   Issue_Type             100 non-null    object
 4   Priority               100 non-null    object
 5   Status                 100 non-null    object
 6   Created_Date           100 non-null    object
 7   Resolved_Date          100 non-null    object
 8   Resolution_Time_Hours  100 non-null    int64
 9   Agent                  100 non-null    object
 10  Customer_Satisfaction  100 non-null    int64
dtypes: int64(2), object(9)
memory usage: 8.7+ KB

In [63]:
#Check Missing Values

df.isnull().sum()

Ticket_ID                0
Customer_ID              0
Region                   0
Issue_Type               0
Priority                 0
Status                   0
Created_Date             0
Resolved_Date            0
Resolution_Time_Hours    0
Agent                    0
Customer_Satisfaction    0
dtype: int64

In [64]:
#Convert Date Columns

df['Created_Date'] = pd.to_datetime(df['Created_Date'], format='%d-%m-%Y')
df['Resolved_Date'] = pd.to_datetime(df['Resolved_Date'], format='%d-%m-%Y')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              100 non-null    object
 1   Customer_ID            100 non-null    object
 2   Region                 100 non-null    object
 3   Issue_Type             100 non-null    object
 4   Priority               100 non-null    object
 5   Status                 100 non-null    object
 6   Created_Date           100 non-null    datetime64[ns]
 7   Resolved_Date          100 non-null    datetime64[ns]
 8   Resolution_Time_Hours  100 non-null    int64
 9   Agent                  100 non-null    object
 10  Customer_Satisfaction  100 non-null    int64
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 8.7+ KB

In [66]:
#Calculate Resolution Time

df['Resolution_Time_Hours'] = (df['Resolved_Date'] - df['Created_Date']).dt.total_seconds() / 3600
df.head()

,Ticket_ID,Customer_ID,Region,Issue_Type,Priority,Status,Created_Date,Resolved_Date,Resolution_Time_Hours,Agent,Customer_Satisfaction
0,T001,C101,North,Login Issue,High,Closed,2025-01-01,2025-01-01,0.0,Rahul,4
1,T002,C102,West,Payment Issue,Medium,Closed,2025-01-01,2025-01-02,24.0,Sneha,5
2,T003,C103,South,Account Locked,High,Closed,2025-01-02,2025-01-02,0.0,Amit,3
3,T004,C104,East,Login Issue,Low,Closed,2025-01-02,2025-01-03,24.0,Neha,4
4,T005,C105,North,Refund Issue,High,Closed,2025-01-03,2025-01-03,0.0,Rahul,5

In [67]:
#Average Res Time is 11.52.
#50% of tickets are resolved on the same day which means actively working.
#Remaining are resolved within 24 hours of raising ticket.

df['Resolution_Time_Hours'].describe()

count    100.000000
mean      11.520000
std       12.050802
min        0.000000
25%        0.000000
50%        0.000000
75%       24.000000
max       24.000000
Name: Resolution_Time_Hours, dtype: float64

#Basic Data Analytics

In [68]:
#Total Tickets

total_tickets = df.shape[0]
print(total_tickets)

100

In [69]:
#Tickets by Region
#Most tickets are raised in the North Region

df['Region'].value_counts()

Region
North    28
West     24
South    24
East     24
Name: count, dtype: int64

In [70]:
#Most Common Issue
#Login issue is common and least commmon is Locked Account

df['Issue_Type'].value_counts()

Issue_Type
Login Issue        24
Payment Issue      20
Refund Issue       20
Technical Error    20
Account Locked     16
Name: count, dtype: int64

In [71]:
#Average Resolution Time
#Approximately 12 hours

df['Resolution_Time_Hours'].mean()

np.float64(11.52)

In [72]:
#Agent Performance
#Neha & Sneha have delayed solving most tickets.

df.groupby("Agent")['Resolution_Time_Hours'].mean().sort_values(ascending=False)

Agent
Neha     24.0
Sneha    24.0
Amit      0.0
Rahul     0.0
Name: Resolution_Time_Hours, dtype: float64

In [73]:
#Customer Satisfaction
#Average satisfaction is from Neha and Rahul

df.groupby("Agent")['Customer_Satisfaction'].mean()

Agent
Amit     3.833333
Neha     4.166667
Rahul    4.428571
Sneha    3.833333
Name: Customer_Satisfaction, dtype: float64

In [74]:
df

,Ticket_ID,Customer_ID,Region,Issue_Type,Priority,Status,Created_Date,Resolved_Date,Resolution_Time_Hours,Agent,Customer_Satisfaction
0,T001,C101,North,Login Issue,High,Closed,2025-01-01,2025-01-01,0.0,Rahul,4
1,T002,C102,West,Payment Issue,Medium,Closed,2025-01-01,2025-01-02,24.0,Sneha,5
2,T003,C103,South,Account Locked,High,Closed,2025-01-02,2025-01-02,0.0,Amit,3
3,T004,C104,East,Login Issue,Low,Closed,2025-01-02,2025-01-03,24.0,Neha,4
4,T005,C105,North,Refund Issue,High,Closed,2025-01-03,2025-01-03,0.0,Rahul,5
...,...,...,...,...,...,...,...,...,...,...,...
95,T096,C121,North,Login Issue,Low,Closed,2025-01-11,2025-01-11,0.0,Rahul,4
96,T097,C122,West,Payment Issue,Medium,Closed,2025-01-11,2025-01-12,24.0,Sneha,5
97,T098,C123,South,Technical Error,High,Closed,2025-01-12,2025-01-12,0.0,Amit,4
98,T099,C124,East,Refund Issue,Medium,Closed,2025-01-12,2025-01-13,24.0,Neha,3
99,T100,C125,North,Account Locked,High,Closed,2025-01-13,2025-01-13,0.0,Rahul,5

#Save Clean Dataset

In [76]:
df.to_csv("clean_support_data.csv", index=False)